export const SEARCH_FOR_ALBUMS = "SEARCH_FOR_ALBUMS";
export const ALBUMS_ERR = "ALBUMS_ERR";
export const GET_SONGS_FROM_ALBUM = "GET_SONGS_FROM_ALBUM";
export const SONG_ERR = "SONG_ERR";
export const RESET_SONGS = "RESET_SONGS";
export const START_LOADING = "START_LOADING";